In [1]:
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
from rdkit import DataStructs
import numpy as np
import pandas as pd

Read in the SMILES of the acids and generate Morgan fingerprints for them

In [2]:
# Read in the acid smiles
smiles_acids = pd.read_csv("amide_smiles_substrates_acids.csv",index_col=0,header=0).index.to_list()
print(f"{len(smiles_acids)} acid SMILES read in.")

66 acid SMILES read in.

In [3]:
# calculate the morgan fingerprints
mols = [Chem.MolFromSmiles(smiles) for smiles in smiles_acids]
# instantiate fingerprint generator
mfp_fpg = rdFingerprintGenerator.GetMorganGenerator(radius = 2, fpSize = 2048)
# create the fingerprints
acid_fps = [list(mfp_fpg.GetFingerprint(mol)) for mol in mols]

print("Finished calculating descriptors!")

Finished calculating descriptors!

In [4]:
# migrate the data into a dataframe
df_acids = pd.DataFrame(acid_fps,index = smiles_acids)
df_acids

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
O=C(O)c1cc2ccccc2s1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)c1ccco1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)c1cccc(-c2ccccc2)c1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CC(C(=O)O)c1ccc(-c2ccccc2)c(F)c1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)C(c1ccccc1)c1ccccc1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCCCOc1ccc(C(=O)O)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)c1ccc(-c2ccccc2)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)C1CCC(F)(F)CC1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)c1ccncc1Cl,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)c1ccccc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# remove columns with missing/ non-numerical data
removed_columns = []
# Iterate over columns to find any with string values
for col in df_acids.columns:
    if df_acids[col].dtype == object or df_acids[col].apply(lambda x: isinstance(x, str)).any():
        removed_columns.append(col)

# Print names of removed columns
print(f"Removed {len(removed_columns)} columns containing string values (indicating errors and missing values):")
print(f"{removed_columns}")

# Drop the columns from the DataFrame
df_acids.drop(columns=removed_columns,inplace=True)
df_acids

Removed 0 columns containing string values (indicating errors and missing values):
[]

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
O=C(O)c1cc2ccccc2s1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)c1ccco1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)c1cccc(-c2ccccc2)c1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CC(C(=O)O)c1ccc(-c2ccccc2)c(F)c1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)C(c1ccccc1)c1ccccc1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCCCOc1ccc(C(=O)O)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)c1ccc(-c2ccccc2)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)C1CCC(F)(F)CC1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)c1ccncc1Cl,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(O)c1ccccc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# save the descriptors
df_acids.to_csv("./../1_Dataset_Generation/Data_For_Individual_Substrates/amide_morgan_descr_acids.csv",index=True,header=True)

Read in the SMILES of the amines and generate morgan descriptors for them

In [7]:
# Read in the amine smiles
smiles_amines = pd.read_csv("amide_smiles_substrates_amines.csv",index_col=0,header=0).index.to_list()
print(f"{len(smiles_amines)} amine SMILES read in.")

70 amine SMILES read in.

In [8]:
# calculate the morgan descriptors
# calculate the morgan fingerprints
mols = [Chem.MolFromSmiles(smiles) for smiles in smiles_amines]
# instantiate fingerprint generator
mfp_fpg = rdFingerprintGenerator.GetMorganGenerator(radius = 2, fpSize = 2048)
# create the fingerprints
amine_fps = [list(mfp_fpg.GetFingerprint(mol)) for mol in mols]

print("Finished calculating descriptors!")

Finished calculating descriptors!

In [9]:
# migrate the data into a dataframe
df_amines = pd.DataFrame(amine_fps,index = smiles_amines)
df_amines

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
Cc1ccc(N)nc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NCc1ccc(F)cc1F,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NCc1ccc(Cl)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
COc1ccc(CN)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
COc1ccc(N)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CC(C)NC(C)C,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cc1ccc(S(N)(=O)=O)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Nc1ccc(Cl)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NCC1CC1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cc1cn(-c2cc(N)cc(C(F)(F)F)c2)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
# remove columns with missing/ non-numerical data
removed_columns = []
# Iterate over columns to find any with string values
for col in df_amines.columns:
    if df_amines[col].dtype == object or df_amines[col].apply(lambda x: isinstance(x, str)).any():
        removed_columns.append(col)

# Print names of removed columns
print(f"Removed {len(removed_columns)} columns containing string values (indicating errors and missing values):")
print(f"{removed_columns}")

# Drop the columns from the DataFrame
df_amines.drop(columns=removed_columns,inplace=True)
df_amines

Removed 0 columns containing string values (indicating errors and missing values):
[]

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
Cc1ccc(N)nc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NCc1ccc(F)cc1F,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NCc1ccc(Cl)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
COc1ccc(CN)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
COc1ccc(N)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CC(C)NC(C)C,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cc1ccc(S(N)(=O)=O)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Nc1ccc(Cl)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NCC1CC1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cc1cn(-c2cc(N)cc(C(F)(F)F)c2)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
# save the descriptors
df_amines.to_csv("./../1_Dataset_Generation/Data_For_Individual_Substrates/amide_morgan_descr_amines.csv",index=True,header=True)

Read in the SMILES of the amide products and generate morgan descriptors for them

In [12]:
# Read in the product smiles
smiles_amide = pd.read_csv("amide_smiles_products.csv",index_col=0,header=0).index.to_list()
print(f"{len(smiles_amide)} amide product SMILES read in.")

632 amide product SMILES read in.

In [13]:
# calculate the morgan descriptors
# calculate the morgan fingerprints
mols = [Chem.MolFromSmiles(smiles) for smiles in smiles_amide]
# instantiate fingerprint generator
mfp_fpg = rdFingerprintGenerator.GetMorganGenerator(radius = 2, fpSize = 2048)
# create the fingerprints
amide_fps = [list(mfp_fpg.GetFingerprint(mol)) for mol in mols]

print("Finished calculating descriptors!")

Finished calculating descriptors!

In [14]:
# migrate the data into a dataframe
df_amide = pd.DataFrame(amide_fps,index = smiles_amide)
df_amide

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
Cc1ccc(NC(=O)c2cc3ccccc3s2)nc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(NCc1ccc(F)cc1F)c1ccco1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(NCc1ccc(Cl)cc1)c1cccc(-c2ccccc2)c1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
COc1ccc(CNC(=O)C(C)c2ccc(-c3ccccc3)c(F)c2)cc1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
COc1ccc(NC(=O)c2cccc(-c3ccccc3)c2)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
COc1ccc(NC(=O)C2CCN(C(=O)OCc3ccccc3)CC2)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
CON(C)C(=O)c1c(C)cc(C)cc1C,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cc1ccc(S(=O)(=O)NC(=O)c2ccc3nc(C)ccc3c2)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cc1ccc(Cl)c(NC(=O)c2ccc3nccnc3c2)c1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(Cc1ccc2c(c1)OCO2)Nc1ccc(Cl)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
# remove columns with missing/ non-numerical data
removed_columns = []
# Iterate over columns to find any with string values
for col in df_amide.columns:
    if df_amide[col].dtype == object or df_amide[col].apply(lambda x: isinstance(x, str)).any():
        removed_columns.append(col)

# Print names of removed columns
print(f"Removed {len(removed_columns)} columns containing string values (indicating errors and missing values):")
print(f"{removed_columns}")

# Drop the columns from the DataFrame
df_amide.drop(columns=removed_columns,inplace=True)
df_amide

Removed 0 columns containing string values (indicating errors and missing values):
[]

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
Cc1ccc(NC(=O)c2cc3ccccc3s2)nc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(NCc1ccc(F)cc1F)c1ccco1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(NCc1ccc(Cl)cc1)c1cccc(-c2ccccc2)c1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
COc1ccc(CNC(=O)C(C)c2ccc(-c3ccccc3)c(F)c2)cc1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
COc1ccc(NC(=O)c2cccc(-c3ccccc3)c2)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
COc1ccc(NC(=O)C2CCN(C(=O)OCc3ccccc3)CC2)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
CON(C)C(=O)c1c(C)cc(C)cc1C,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cc1ccc(S(=O)(=O)NC(=O)c2ccc3nc(C)ccc3c2)cc1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cc1ccc(Cl)c(NC(=O)c2ccc3nccnc3c2)c1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=C(Cc1ccc2c(c1)OCO2)Nc1ccc(Cl)cn1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
# save the descriptors
df_amide.to_csv("./../1_Dataset_Generation/Data_For_Individual_Substrates/amide_morgan_descr_prods.csv",index=True,header=True)